[workspace]

members = [
    "ffplayout-api",
    "ffplayout-engine",
    "lib",
]

default-members = [
    "ffplayout-api",
    "ffplayout-engine",
    "lib",
]

[profile.release]
opt-level = 3
strip = true
lto = true
