# cargo-features = ["strip"]

[package]
name = "ffplayout-engine-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[[bin]]
name = "ffplayout"
path = "src/main.rs"

[profile.release]
# strip = true
lto = true
