[package]
name = "ffplayout-rs"
description = "24/7 playout based on rust and ffmpeg"
license = "GPL-3.0"
version = "0.9.1"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "3.1", features = ["derive"] }
ffprobe = "0.3"
file-rotate = "0.6"
jsonrpc-http-server = "18.0"
lettre = "0.10.0-rc.5"
log = "0.4"
notify = "4.0"
once_cell = "1.10"
process_control = "3.3"
rand = "0.8"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
shlex = "1.1"
simplelog = { version = "^0.11", features = ["paris"] }
tokio = { version = "1.16", features = ["rt-multi-thread"] }
walkdir = "2"

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[[bin]]
name = "ffplayout"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = true
lto = true
