# cargo-features = ["strip"]

[package]
name = "ffplayout-engine-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
regex = "1"
chrono = "0.4"
clap = { version = "3.0.14", features = ["derive"] }
notify = "4.0.0"
walkdir = "2"
rand = "0.8.5"
# tokio = { version = "1.16.1", features = ["full"] }

[[bin]]
name = "ffplayout"
path = "src/main.rs"

[profile.release]
# strip = true
lto = true
