# cargo-features = ["strip"]

[package]
name = "ffplayout-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "3.1.6", features = ["derive"] }
ffprobe = "0.3"
file-rotate = "0.6.0"
lettre = "0.10.0-rc.4"
log = "0.4.14"
notify = "4.0.17"
rand = "0.8.5"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
simplelog = { version = "^0.11.2", features = ["paris"] }
tokio = { version = "1.16.1", features = ["full"] }
walkdir = "2"

[[bin]]
name = "ffplayout"
path = "src/main.rs"

[profile.release]
# strip = true
lto = true
