name: rust
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: On all Systems
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup component add clippy

      - name: Run on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
        run: cargo fmt --all -- --check
        run: cargo clippy --all-features --all-targets -- --deny warnings
        run: cargo build --all-features

      - name: Run on macOS/Windows
        run: cargo build --all-features
